### ISSUE TITLE
Move the close "x" into payments-ui

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments-ui#106]
Currently there's a close x in the payments-client that closes the iframe. We've also got code in payments-ui that post message back to payments-client.

If we move the close into the payments-ui and send a post message back with cancelled, it will be more consistent and prevent problems of the "x" appearing before the rest of the frame and attach google analytic events to the close.

**Comment by muffinresearch** [comment]
I've talked this over with kumar. The need to close the modal seems to make sense to stay on the client. You can also click outside the modal to close it currently too.

We should be able to track closure from the client-side with iframe unload events.

I'm going to be moving the icon and some of the basic modal styles back to the client for the perception of performance, plus to enable the user to kill the modal if the iframe should fail to load for any reason.
