### ISSUE TITLE
Delete payment methods in the management interface

### ISSUE THREAD

**Issue by andymckay** [mozilla/payments-ui#164]
Provide a way to delete a payment method in the management interface. UX is being worked on by @brampitoyo, but when the delete occurs, a warning about any existing subscriptions will be raised.

Supports mozilla/payments#85

**Comment by kumar303** [comment]
This landed in https://github.com/mozilla/payments-ui/pull/255 and https://github.com/mozilla/payments-service/pull/123

**Comment by muffinresearch** [comment]
I raised a separate bug about dealing with existing subs here: #273
