### ISSUE TITLE
Split data reducer tests into separate files

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-ui#224]
https://github.com/mozilla/payments-ui/pull/221 moved data stores into separate files but we forgot to split the tests into separate files as well.

**Comment by muffinresearch** [comment]
Good call, I was also thinking it might be nice to split the tests up a bit more into dirs for relevant bits. Just so it's clearer what tests are for components, stores, actions etc? That might make it more obvious where coverage is lacking too.

**Comment by kumar303** [comment]
yeah, matching unit test files to code files is always helpful

**Comment by muffinresearch** [comment]
Oops pressed the wrong button.
