### ISSUE TITLE
Protect against undefined action types better

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-ui#229]
When creating redux stores it's easy to do something like this:
````
export myStore(state, action) {
  if (action.type === actionTypes.NEW_THING) {
    ...
  }
}
````
and forget to put `NEW_THING` in the constants. This will create a true expression! That's because `action.type` seems to be undefined sometimes for a weird reason (might be a bug).

I took a stab at it using getters but didn't get it working so I'm just filing this to try it again later.

**Comment by muffinresearch** [comment]
Maybe a line in the logger middleware to check? It can just warn on the undefined action.
