### ISSUE TITLE
Show sign-in screen when management page loads

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-ui#234]
We don't have UX mocks for this but in order to do anything in the management interface you have to sign-in. Let's try it this way:

1. If an access token was passed on the query string, verify the token as normal (this already happens as of https://github.com/mozilla/payments-ui/pull/230)
2. Otherwise, immediately show a sign-in screen by calling `fxaClient.auth.signIn()`

We could also maybe optimize repeat visits by storing a refresh token.

**Comment by muffinresearch** [comment]
We should definitely ask the question of the FxA team "does the login need to come from a click?". I think there's going to be some case where it does even if we can get away with it on desktop.

**Comment by kumar303** [comment]
This was fixed in https://github.com/mozilla/payments-ui/pull/266
