### ISSUE TITLE
Use notifications for error messages

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments-ui#282]
In the management interface:

![7alhwojkqj7dr8eoz_hdsv3pmglkd4ccyrjzshxrice](https://cloud.githubusercontent.com/assets/1514/9134441/10c8751e-3cfc-11e5-9c84-88e6143f0471.png)

**Comment by muffinresearch** [comment]
This just some leftover from  old layout.

**Comment by muffinresearch** [comment]
Could use some ux-input here on how we want to represent general errors in the managment interface.

**Comment by brampitoyo** [comment]
**Decision:** first, design notification flag, then we can use it to display errors and take action (e.g. “try again”) a la Gmail.

**Comment by brampitoyo** [comment]
How about an error message like this one?

![ux-management-error](https://cloud.githubusercontent.com/assets/51007/9190637/83891cbe-404b-11e5-9988-aff86ea99a2f.png)

**Comment by tofumatt** [comment]
As a notification that looks nice, but for errors in particular would some red colour be alright? Might draw a bit more attention and also signal something definitely went wrong.



- tofumatt

**Comment by brampitoyo** [comment]
Yep. Some red would definitely be alright. How does this look?

![ux-management-wireframe-error](https://cloud.githubusercontent.com/assets/51007/9266733/4ab38fbe-4299-11e5-86ee-3142edbff9c4.png)

**Comment by tofumatt** [comment]
Reads much more like an error 😃. Nice! 👍



- tofumatt

**Comment by muffinresearch** [comment]
Relates to #413
