### ISSUE TITLE
Need a decent title

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments-ui#286]
The <title> for the management interface is just "Management", it should be something related to the function that the page is on.

**Comment by brampitoyo** [comment]
What about something like “Firefox Accounts Payments”? Too obvious?

**Comment by muffinresearch** [comment]
To do a long string like that it would probably need to be a suffix otherwise that's all you'd see in a tab.

**Comment by andymckay-limited-access** [comment]
I was just going to do Pay then Pay | My account etc...

**Comment by brampitoyo** [comment]
Sounds good to me. We can change it later should we have problems with the name.
