### ISSUE TITLE
Implement management sign out

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-ui#314]
We have [new mocks](http://payments.readthedocs.org/en/latest/_images/ux-management-wireframe-wide.png) for sign out so let's hook it up. There are some skipped tests for how it used to work (with the old button) so the code is pretty much all there. The sign out data state should already happen naturally. The view at sign out time will be the initial sign-in page as if you loaded the app for the first time.

**Comment by muffinresearch** [comment]
Styles are landed so this is ready to go.
