### ISSUE TITLE
Rename Subscription -> Product

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/payments-ui#330]
A subscription is a bit too specific and hard-wired to the initial case we're looking at. 

If we had ProductList and Product instead of SubscriptionList and Subsription it would be a bit more flexible going forward.

**Comment by kumar303** [comment]
I think it might be too early to rename this because the UX around one-time purchased products could be totally different

**Comment by kumar303** [comment]
Looks like I need to do some of this for https://github.com/mozilla/payments-ui/issues/339 but I'm not sure if I'll get everything

**Comment by kumar303** [comment]
it was mostly fixed in https://github.com/mozilla/payments-ui/pull/352
