### ISSUE TITLE
Create a better signed-out view

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-ui#334]
We decided we need a signed-out view in the management app. See it in action here (gif screencast)  https://github.com/mozilla/payments-ui/pull/328 The user will only see this if they click the sign-out button. That is, when the page first loads they won't see it; they will be prompted to sign in automatically.

Bram, can you help us figure out the best UX for this?

Here are its key points:
* It needs to let the user sign back in
* It needs to hide links to all other pages
* This will serve as the background for the FxA sign-in overlay (which we don't really have control over)

**Comment by brampitoyo** [comment]
What do you think about using either one of these four options? (I like the two on the right-hand side the best).

![ux-management-wireframe-signed-out](https://cloud.githubusercontent.com/assets/51007/9266365/204b7868-4294-11e5-8160-340f1fb90891.png)

**Comment by kumar303** [comment]
Cool. I like the one in the upper right the best -- the dark background with the centered sign-in. I think that will work best because the FxA sign-in overlay is white and it's also centered.

**Comment by brampitoyo** [comment]
The only objection I have against that design is that the transition between the dark background of the sign-in page and the mostly-light background of the management interface will be jarring, but I think it’s a very minor issue.

**Comment by kumar303** [comment]
The bottom right (light background) would work fine too. I think the ones that retain the lefthand sidebar would be odd because the FxA overlay will be centered.

**Comment by kumar303** [comment]
I'll take a stab at it

**Comment by kumar303** [comment]
@brampitoyo I went with the lighter background one but funny enough, the FxA overlay dims the background and we don't really have control over that. You can see it in action here: https://github.com/mozilla/payments-ui/pull/341

**Comment by kumar303** [comment]
I merged in the light background one. After about 10 minutes, it should be visible on the dev site: http://pay.dev.mozaws.net:8000/management.html
