### ISSUE TITLE
Payments failing

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments-ui#349]
I'm betting this is related to recent donations changes so giving that label.

On starting a payment, after completing the FxA login, I get an error in the console: "Invalid product: undefined".

https://www.dropbox.com/s/msk88s98szazvac/Screenshot%202015-08-19%2016.47.06.png?dl=0

Reproducible locally and on http://pay.dev.mozaws.net/.

**Comment by andymckay-limited-access** [comment]
Is the result of # appearing in the URL? 

http://pay.dev:8000/?access_token=...&product=mozilla-concrete-brick fails
http://pay.dev:8000/#/?access_token=...&product=mozilla-concrete-brick works

**Comment by andymckay-limited-access** [comment]
Bisect says its https://github.com/mozilla/payments-ui/commit/e5e8b1cf3c81bb2eadce4e4d325d68f27a512f7d

**Comment by andymckay-limited-access** [comment]
The # causes this split to ignore everything else: https://github.com/mozilla/payments-ui/blob/master/public/js/utils.jsx#L75

**Comment by kumar303** [comment]
Aha! Good spotting, sorry about that. I was getting this error too but I didn't have time to pin it down.

r? https://github.com/mozilla/payments-ui/pull/350

**Comment by andymckay-limited-access** [comment]
This is caused by this change. Looks like there's a good reason for it. https://github.com/mozilla/payments-client/commit/0e4905471d5afa2f1f8653c66973c174c68efced
