### ISSUE TITLE
Restrict anonymous payments to supported products

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-ui#355]
Right now we're pretty sure donations will be the only products that can be paid for anonymously. Out of paranoia, I was thinking that maybe we should prevent an anonymous payment for anything except donations. Does that seem helpful or overkill? Otherwise the user may not have any way to get at the product. The current plan in https://github.com/mozilla/payments-service/issues/134 is to allow anonymous payments for anything.

**Comment by andymckay** [comment]
Seems valid. I think we should be doing that check in payments-service and surfacing an error back up to payments-ui.

**Comment by andymckay** [comment]
I'd really like to break down the authentication options into seperate configs so there's more fine granularity over this than just "donations" or "products". But that's something we don't need to worry about right now.

**Comment by kumar303** [comment]
oh, yeah, whoops. I meant to file this in payments-service

**Comment by kumar303** [comment]
moved to https://github.com/mozilla/payments-service/issues/144
