### ISSUE TITLE
Add email into the payment flow

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments-ui#358]
Add in email into the payment flow if its required as per the config. @brampitoyo had this in earlier mocks, so we can probably just use that for now.

Supports: https://github.com/mozilla/payments/issues/117

**Comment by brampitoyo** [comment]
Reference design:

![ux-pay-wireframe-email](https://cloud.githubusercontent.com/assets/51007/9430440/142a53c0-4a4a-11e5-9962-e9c0579372cb.PNG)
