### ISSUE TITLE
Show email address after submitting a recurring donation

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-ui#376]
After completing a recurring donation with an email address, the completion page should show that email. Currently it shows nothing because it's looking for the signed in user's email.

Supports https://github.com/mozilla/payments/issues/117

**Comment by brampitoyo** [comment]
Reference design:
![ux-pay-wireframe-receipt-sent](https://cloud.githubusercontent.com/assets/51007/9569763/c2a0bf6a-4fc8-11e5-93cd-37cf765aa35c.PNG)

But perhaps we say “Donation accepted” instead?

**Comment by kumar303** [comment]
I was wondering about this too. "Payment" doesn't seem right. Donation accepted sounds better.

**Comment by tofumatt** [comment]
Agreed, "donation accepted" or even "donation sent" seems better. You're sending/gifting a donation so it feels more personal to say it's been sent successfully than "the processor accepted it", but maybe that's just me being picky ;-)



- tofumatt

**Comment by amuntner** [comment]
Agree with Tofumatt, 'donation sent' is the best descriptive text.

**Comment by brampitoyo** [comment]
Yes. I like ‘donation sent’.

Here are a few others we might want to consider:
* Thank you!
* Thank you for your generous support
* Thank you for your gift
* Thank you for donating to [vendor_name]
