### ISSUE TITLE
Handle signed-in users when processing an email-only donation

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-ui#378]
When submitting a donation (one-time or recurring), the user can enter an email address. If they are already signed in but the email they enter is *different* from their signed-in email then the backend endpoint will get confused. You'll see an error like 'buyer does not exist' when creating the donation. We could fix this by either signing out first from the UI to clear the cookie (that's good as a quick fix) or disallow a custom email entry when the user is signed in. In other words: show their email address at the top so that they know they are subscribing with their existing user account.

**Comment by muffinresearch** [comment]
Easiest way to handle this as a quick fix is to show any email on the user object in the email field and if pre-populated just disable that field.

**Comment by kumar303** [comment]
Correction on this: we don't actually have automatic user sign-in logic within the UI. However, the browser might have a cookie left over from when they last signed in. This means the backend will know the user is signed in but the UI will not. Thus, the least effort fix here is to clear the cookies, not to pre-populate the email field like we had discussed.

**Comment by kumar303** [comment]
This is a bit harder than I thought. As a quicker fix, I am proposing to just raise an error in the API: https://github.com/mozilla/payments-service/pull/153
