### ISSUE TITLE
Show general payment processing errors

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-ui#411]
When processing a payment, the user does not see any general processing error, i.e. one not associated with a form field. They see either an empty credit card form or a spinner but no error message. This is pretty bad because there are a lot of errors that could happen like: https://developers.braintreepayments.com/javascript+python/reference/general/testing#unsuccessful-credit-card-verification

There is a UX mock for how this should look (the last screen here):
![ux-pay-form-error](https://cloud.githubusercontent.com/assets/55398/9740833/69899b86-561c-11e5-8c9a-5e933742233f.png)

**Comment by muffinresearch** [comment]
Relates to #413

**Comment by muffinresearch** [comment]
Possibly crosses over with #95.
