### ISSUE TITLE
Add in localisation framework

### ISSUE THREAD

**Issue by andymckay** [mozilla/payments-ui#47]
This is about adding a way to do localisations on the front end and the scripts for passing it up to verbatim so it can be localised. We should start this sooner rather than later so that we've got time to tell people about the localisation project and start addressing any issues.

Suspecting this is very similar to what was done for spartacus.

**Comment by muffinresearch** [comment]
Yeah I'll aim to use i18n-abide again. The bigger question is what we should do with the index.html.

The two choices I see are:

* Stand-up express so we can run a middleware to set lang attrs.
* Keep it static and generate an index page for each locale.

I quite like the latter. Would mean we'd need some nginx config / plugins to handle the headers and redirect appropriately.

I'm thinking we could also consider making localised bundles for the app too.

The immediate place to start is with extraction. At least this way localisation can start whilst we decide on the technical implementation.
