### ISSUE TITLE
Make month and year seperate inputs

### ISSUE THREAD

**Issue by andymckay** [mozilla/payments-ui#64]
In @brampitoyo latest mocks month and year are two seperate inputs.

**Comment by muffinresearch** [comment]
@brampitoyo is there a rationale for sepearate inputs? I was thinking the way it is now with the masking works well and allows the card-validator lib to validate the date as one.

**Comment by brampitoyo** [comment]
I fixed the mocks so that month and year inputs are unified under one field. The two-field approach was an early design that unfortunately got carried over to the wireframes when I copy-and-pasted stuff around.

Sorry about that. No change needed here. The current form field is perfect.
