### ISSUE TITLE
Set up Google Analytics

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments-ui#74]
Analytics everywhere, let's create an client id and account for payments and add that in.

Then we'll need to start sprinkling events across the payments-ui like fairy dust.

**Comment by andymckay-limited-access** [comment]
Request for id is: https://bugzilla.mozilla.org/show_bug.cgi?id=1170652

**Comment by muffinresearch** [comment]
We should also add an unload handler. This will allow us to track closures from payments-client.

**Comment by muffinresearch** [comment]
Following the mozwww discussions let's try and improve how we refer to events to make it super-clear what an event is for.
