### ISSUE TITLE
replace jquery with fetch polyfill

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-ui#84]
I don't think we're using JQuery for anything other than its XHR abstraction, right? We could replace it with the ES6 fetch polyfill: https://github.com/github/fetch :
````
fetch('/users.json')
  .then(function(response) {
    return response.json()
  }).then(function(json) {
    console.log('parsed json', json)
  }).catch(function(ex) {
    console.log('parsing failed', ex)
  })
````

**Comment by muffinresearch** [comment]
Nothing I can't get rid of easily. :+1:

**Comment by muffinresearch** [comment]
Would be good to start graphing the bundle sizes. If only to see it drop considerably when we remove Jquery :)

**Comment by kumar303** [comment]
+1

we would need the obligatory http://arepaymentsslimyet.com of course

**Comment by kumar303** [comment]
This could also be our chance to add a networking layer that can be easily mocked/stubbed for testing. For example, we want to be able to make assertions about how components use their state to do API requests and how they set state based on responses.
