### ISSUE TITLE
Make the end page look like the mock

### ISSUE THREAD

**Issue by andymckay** [mozilla/payments-ui#88]
The mock looks like this:

![screenshot 2015-06-08 16 05 44](https://cloud.githubusercontent.com/assets/74699/8047330/af98a50c-0df8-11e5-8692-c3f64273c098.png)

This will require us to know the email, which @kumar303 is on in bug mozilla/payments-service#35

**Comment by andymckay-limited-access** [comment]
I'll note this doesn't have an obvious call to action or button to press to close. I like @muffinresearch mocks which have a big "OK" button on the bottom.

https://www.dropbox.com/s/zlp58m3s0jy3gpj/Screenshot%202015-06-10%2009.43.07.png?dl=0

Would that be ok, @brampitoyo or was there another UX interaction here?

**Comment by andymckay-limited-access** [comment]
I think this is done, no comment from @brampitoyo, so assent assumed :)

**Comment by andymckay-limited-access** [comment]
![screenshot 2015-06-18 14 34 57](https://cloud.githubusercontent.com/assets/11861185/8242841/35d86b2c-15c7-11e5-89e8-8ad781d24de3.png)

**Comment by andymckay-limited-access** [comment]
Although this shows the difference between Clear Sans (rest) and Fira Sans Light (product).

**Comment by brampitoyo** [comment]
Small font usage tweak:

Fira Sans Light (weight: 200)
* Price and currency values
* “Payment Accepted”

Fira Sans Regular
* Vendor name
* Product name
* “per month”

Clear Sans Regular
* “Your receipt has been sent to…”
* Button text

We can tweak it in person next week. It’s not a big issue. Just a small refinement.
