### ISSUE TITLE
Improve the layout of the payment-complete page

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/payments-ui#96]
The css is quite hacky just to get something that's up and running. Let's shore up the layout and make sure it responds to different sizes of display a bit better.

**Comment by andymckay-limited-access** [comment]
It looks better now, but not exactly sure what this bug details.

**Comment by muffinresearch** [comment]
> It looks better now, but not exactly sure what this bug details.

The hackyness was the absolute positioned button which was just a quick hack. Looks like you've removed that already so I'll take a look and some more specifics if there's anything else needing to be done.

**Comment by muffinresearch** [comment]
In fact better still, I'll close this and open new issues for anything else.
